<?php

use Illuminate\Database\Seeder;

class GenreTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $genres = [
            "2D action, platformer",
            "2D action, platformer, beat-'em-up",
            "2D platform, action",
            "3D shooter",
            "Action",
            "Action Adventure",
            "Action role-playing",
            "Action role-playing video game",
            "Action RPG",
            "Action-adventure",
            "Action-adventure, Platformer",
            "Action-adventure, platforming",
            "Action-platformer",
            "Action, Beat em up",
            "Action, Flight simulator",
            "Action, maze",
            "Action, platform",
            "Action, Platform, Action",
            "Action, Platformer",
            "Action, platforming",
            "Action, puzzle",
            "Action, role-playing game",
            "Action, Run and gun",
            "Action, side-scrolling, platformer",
            "American football simulation",
            "Arcade",
            "Arcade racing",
            "Art tool",
            "Artillery, Strategy",
            "Beat 'em up",
            "Beat 'em up, platformer, action",
            "Beat'em up",
            "Boxing",
            "Breakout",
            "Castlevania: Legacy of Darkness",
            "Cinematic platformer",
            "Cinematic platformer, action-adventure",
            "City-building",
            "City-building game",
            "Combat flight simulator",
            "Construction and management sim",
            "Driving, Racing",
            "Edutainment, Maze, Shooter game",
            "Farm simulation, role-playing game",
            "Fighting",
            "Fighting game, beat 'em up, action, platformer",
            "First-person shooter",
            "Flight simulation",
            "Football",
            "Formula One, racing",
            "Kart racing",
            "Light gun shooter",
            "Maze",
            "Modern jet flight simulator",
            "Multidirectional shooter",
            "Music game",
            "Party",
            "Party, sports",
            "Pinball",
            "Platform",
            "Platform-adventure",
            "Platform, city-building, simulation",
            "Platform, Hack and slash",
            "Platformer",
            "Platformer, action",
            "Platformer, run and gun",
            "Puzzle",
            "Puzzle, Adventure",
            "Puzzle, platformer",
            "Puzzle, Real-time strategy",
            "Racing",
            "Racing game",
            "Racing, action",
            "Rail shooter",
            "Rail shooter, Puzzle, Light gun shooter",
            "Rail shooter, Shoot 'em up",
            "Real-time strategy",
            "Role-playing",
            "Run and gun",
            "Run and gun, Platform",
            "Sci-fi mech simulation",
            "Scrolling beat 'em up",
            "Scrolling shoot'em up",
            "scrolling shooter",
            "Shoot 'em up",
            "Shoot 'em up, Strategy",
            "Shooter",
            "Shooting gallery",
            "Side-scrolling, beat 'em up",
            "Side-scrolling, puzzle, platformer",
            "Sim racing",
            "Simulation",
            "Snowboarding/skiing",
            "Sports",
            "Sports (Golf)",
            "Sports-based Fighting",
            "sports, golf",
            "Sports, Ice Hockey Sim",
            "Sports, soccer",
            "Sports, Tennis",
            "Strategy",
            "Strategy, Scrolling Shooter",
            "Tank simulation",
            "Third-person adventure",
            "Traditional baseball simulation",
            "Traditional basketball, simulation",
            "Traditional golf, simulation",
            "Traditional ice hockey, simulation",
            "Traditional soccer, simulation",
            "Vehicular combat, Racing",
            "unknown"
        ];

        foreach ($genres as $key => $genre) {
            DB::table('games_genres')->insert([
                'genre' => $genre,
                'description' => null,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now()
            ]);
        }
    }
}
